services:
  nginx:
    image: nginx:latest
    volumes:
      - ./backend/public:/var/www/reutskiy-a.ru/backend/public
      - ./backend/storage/app/public:/var/www/reutskiy-a.ru/backend/storage/app/public
      - ./_docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./_docker/logs/nginx_error.log:/var/log/nginx/error.log
    ports:
      - 127.0.1.1:8080:80
    restart: always
    container_name: nginx_reutskiy-a.ru
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: _docker/Dockerfile
    volumes:
      - ./backend/:/var/www/reutskiy-a.ru/backend
      - ./_docker/logs/php_error.log:/var/log/php_error.log
    restart: always
    container_name: php-fpm_reutskiy-a.ru
